name: Setup Node and Dependencies
description: Checkout code, setup Node.js and install npm dependencies

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "npm"

    - name: Install dependencies
      run: npm clean-install --save-dev

    - name: Generate types
      run: npm run generate:types
