# Top-level configuration
name = "community-hub"
main = "api/src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = ["nodejs_compat"]
keep_vars = false
send_metrics = false
workers_dev = true
preview_urls = false

[triggers]
# Every day at 2:00 am
crons = [ "0 2 * * *" ]

[dev]
host = "localhost"
port = 4242
local_protocol = "http"
upstream_protocol = "https"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
binding = "Assets"
directory = "./public/"
not_found_handling = "none"
html_handling = "auto-trailing-slash"

[vars]
NODE_ENV = "local"
BASE_URL = "http://localhost:4242"
FRONTEND_URL = "http://localhost:3000"

[[d1_databases]]
binding = "Database"
database_name = "vms-local"
database_id = "vms-local"
preview_database_id = "vms-local"
migrations_table = "migrations"
migrations_dir = "db/migrations"

[[kv_namespaces]]
binding = "SessionTokens"
id = "vms-local-session-token"
preview_id = "vms-local-session-token"

[[kv_namespaces]]
binding = "ActivationTokens"
id = "vms-local-activation-token"
preview_id = "vms-local-activation-token"

[[kv_namespaces]]
binding = "PasswordResetToken"
id = "vms-local-password-reset-token"
preview_id = "vms-local-password-reset-token"

[[r2_buckets]]
binding = "ExportedFiles"
bucket_name = "vms-local-exported-files"

# DEV env configurations
# The following placeholder vars will be substituted at run time in GitHub Actions using envsubst
[env.dev.vars]
NODE_ENV = "development"
SENDER_EMAIL = "${DEV_COMM_HUB_SENDER_EMAIL}"
BASE_URL = "https://vms-dev.torontojs.com"
FRONTEND_URL = "https://volunteer-dev.torontojs.com"

[env.dev.assets]
directory = "dist/client"
binding = "Assets"
not_found_handling = "none"
html_handling = "auto-trailing-slash"

[[env.dev.d1_databases]]
binding = "Database"
database_name = "${DEV_COMM_HUB_D1_DB_NAME}"
database_id = "${DEV_COMM_HUB_D1_DB_ID}"
migrations_table = "migrations"
migrations_dir = "db/migrations"

[[env.dev.kv_namespaces]]
binding = "SessionTokens"
id = "${DEV_COMM_HUB_SESSION_TOKENS_ID}"
preview_id = "vms-dev-session-tokens"

[[env.dev.kv_namespaces]]
binding = "ActivationTokens"
id = "${DEV_COMM_HUB_ACTIVATION_TOKENS_ID}"
preview_id = "vms-dev-activation-tokens"

[[env.dev.kv_namespaces]]
binding = "PasswordResetToken"
id = "${DEV_COMM_HUB_PASSWORD_RESET_TOKENS_ID}"
preview_id = "vms-dev-password-reset-token"

[[env.dev.r2_buckets]]
binding = "ExportedFiles"
bucket_name = "vms-exported-files"

# PRODUCTION env configuration
[env.production.vars]
NODE_ENV = "production"
SENDER_EMAIL = "${PROD_COMM_HUB_SENDER_EMAIL}"
BASE_URL = "https://vms.torontojs.com"
FRONTEND_URL = "https://volunteer.torontojs.com"

[env.production.assets]
directory = "dist/client"
binding = "Assets"
not_found_handling = "none"
html_handling = "auto-trailing-slash"

[[env.production.d1_databases]]
binding = "Database"
database_name = "${PROD_COMM_HUB_D1_DB_NAME}"
database_id = "${PROD_COMM_HUB_D1_DB_ID}"
migrations_table = "migrations"
migrations_dir = "db/migrations"

[[env.production.kv_namespaces]]
binding = "SessionTokens"
id = "${PROD_COMM_HUB_SESSION_TOKENS_ID}"
preview_id = "vms-production-session-tokens"

[[env.production.kv_namespaces]]
binding = "ActivationTokens"
id = "${PROD_COMM_HUB_ACTIVATION_TOKENS_ID}"
preview_id = "vms-production-activation-tokens"

[[env.production.kv_namespaces]]
binding = "PasswordResetToken"
id = "${PROD_COMM_HUB_PASSWORD_RESET_TOKENS_ID}"
preview_id = "vms-production-password-reset-token"

[[env.production.r2_buckets]]
binding = "ExportedFiles"
bucket_name = "vms-exported-files"
