name: "Setup Node and Dependencies"
description: "Checkout code, setup Node.js and install npm dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"
      shell: bash

    - run: npm ci
      shell: bash
