name: Apply Labels to Pull Request

on:
  pull_request_target:
    branches:
      - "main"
      - "dev"

jobs:
  pr-labeler:
    name: Apply PR labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v5
