name: CI Checks

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm clean-install --save-dev

      - name: Generate types
        run: npm run generate:types

      - name: Lint all files
        run: npm run lint

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm clean-install --save-dev

      - name: Check files formatting
        run: npm run format:check
