name: CI Tests

on:
  pull_request:
    types:
      - "ready_for_review"

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    concurrency:
      group: ci-unit-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run unit tests
        run: npm test:unit

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    concurrency:
      group: ci-api-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Setup database
        run: |
          yes | npm run db:setup
          npm run db:seed

      - name: Build server
        run: npm run build

      - name: Start preview server (background)
        run: |
          npx vite preview &
          echo $! > preview.pid
          sleep 5

      - name: Run API tests
        run: npm run test:api

      - name: Kill preview server
        if: always()
        run: |
          if [ -f preview.pid ]; then
            kill $(cat preview.pid)
          fi

  # TODO: setup playwright integration tests
  # integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: ci-integration-tests-${{ github.workflow }}-${{ github.ref }}
  #     cancel-in-progress: true

  #   steps:
  #     - name: Setup Node
  #       uses: ./.github/actions/setup-node

  #     - name: Run integration tests
  #       run: npm test:integration
