name: Close Stale Issues and PRs

on:
  workflow_dispatch:
  schedule:
    # Every day at 1:30 AM UTC
    - cron: "30 1 * * *"

jobs:
  close-stale:
    name: Close Stale Issues and PRs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          start-date: 2025-07-01T00:00:00Z

          # Issue
          stale-issue-message: "This issue is stale because it has been open 160 days with no activity."
          days-before-issue-stale: 160
          days-before-issue-close: -1
          stale-issue-label: "Stale 🪨"
          close-issue-label: "Stale Closed 🔒"
          close-issue-reason: not_planned
          exempt-issue-labels: "Important ⚠️"

          # PR
          stale-pr-message: "This PR is stale because there was no activity in the last 20 days. Remove the stale label or this PR will be closed in 30 days"
          days-before-pr-stale: 20
          days-before-pr-close: 30
          stale-pr-label: "Stale 🪨"
          close-pr-label: "Stale Closed 🔒"
