name: Dependency Review

on:
  push:
    branches:
      - "main"
      - "dev"
    paths:
      - "package.json"
      - "package-lock.json"
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          fail-on-scopes: runtime, development
          comment-summary-in-pr: always
          deny-packages: pkg:npm/foobar
