name: Lint project files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto_lint:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint all files
        run: |
          npm run lint
